version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - maria_db
  maria_db:
    container_name: maria_db
    image: "mariadb:latest"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: MDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root