version: "3.7"
services:
  maria_db:
    image: "mariadb:latest"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: MDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root